name: primehub-systems
region: sgp1

services:
  # Main Web Application
  - name: web
    github:
      repo: BisoyJan/primehub-systems
      branch: main
      deploy_on_push: true

    build_command: |
      # Install PHP dependencies
      composer install --optimize-autoloader --no-dev --no-interaction
      
      # Generate Wayfinder routes for type-safe routing
      php artisan wayfinder:generate --with-form
      
      # Install and build frontend assets
      npm ci --prefer-offline
      npm run build

    run_command: |
      # Create storage symlink
      php artisan storage:link || true
      
      # Run database migrations
      php artisan migrate --force
      
      # Optimize application
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan event:cache
      
      # Start the web server
      heroku-php-nginx -C nginx.conf public/

    environment_slug: php
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs

    envs:
      # Application Settings
      - key: APP_NAME
        value: "PrimeHub Systems"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: APP_URL
        value: ${APP_URL}
      
      # Logging
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: warning
      
      # Session & Cache
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_ENCRYPT
        value: "true"
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: database
      
      # Queue
      - key: QUEUE_CONNECTION
        value: database
      
      # Filesystem
      - key: FILESYSTEM_DISK
        value: local
      
      # Database Connection
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_DATABASE
        value: ${db.DATABASE}
      - key: DB_USERNAME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      
      # Mail Configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_FROM_NAME
        value: "PrimeHub Systems"

  # Background Queue Worker
  - name: worker
    github:
      repo: BisoyJan/primehub-systems
      branch: main
      deploy_on_push: true

    build_command: |
      composer install --optimize-autoloader --no-dev --no-interaction

    run_command: |
      php artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --memory=256

    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      # Application Settings
      - key: APP_NAME
        value: "PrimeHub Systems"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      
      # Logging
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: warning
      
      # Database Connection
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_DATABASE
        value: ${db.DATABASE}
      - key: DB_USERNAME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      
      # Queue & Cache
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      
      # Mail (for sending notifications from queue)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        scope: RUN_TIME
        type: SECRET
      - key: MAIL_FROM_NAME
        value: "PrimeHub Systems"

# MySQL Database
databases:
  - name: db
    engine: MYSQL
    version: "8"
    production: true
    size: db-s-1vcpu-1gb
