[program:primehub-queue]
command=/usr/bin/php /var/www/primehub-systems/artisan queue:work --sleep=3 --tries=1 --timeout=1800
autostart=true
autorestart=true
user=primehub
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/primehub-queue.log
stopwaitsecs=3600

[program:primehub-reverb]
command=/usr/bin/php /var/www/primehub-systems/artisan reverb:start --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
user=primehub
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/primehub-reverb.log
stopwaitsecs=3600
